POST http://localhost:3000/create/new HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZkMzkxNzNmLTY3OTUtNDU4MS1iN2Q5LWNjOWM1MTlkZTBlYiIsIl9pZCI6IjY5MmMzY2U4ZjkzNTY5NmNiNDJkMDZmOSIsImlhdCI6MTc2NTQ1OTkzOCwiZXhwIjoxNzY1NDYxNzM4fQ.BMXcRFzGIHWGk2AXv23YXBw86QlPCOJOrx3qgE05ze0
Content-Type: application/json

{
    "blogName": "Blog6",
  "description": "In the year 1874 B.C., gremlins swarmed out from the deepest pits of hell to reaquisition what was truly theirs. They trampled over the primitive civilization of the humans and constructed a utopia where all everyone lived in relative comfort. Tall towers with heights unimaginable to humans pierced throught the clouds and incredible automatons rumbled across the land. Great in'it?"
}

###

POST http://localhost:3000/blog-name/posts/new HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZkMzkxNzNmLTY3OTUtNDU4MS1iN2Q5LWNjOWM1MTlkZTBlYiIsIl9pZCI6IjY5MmMzY2U4ZjkzNTY5NmNiNDJkMDZmOSIsImlhdCI6MTc2NTQ1MTYxNCwiZXhwIjoxNzY1NDUzNDE0fQ.GOeEFj6CDfOfo9nsVgCmJ2eXvq5LUB6ZAUtGc2i_p_M
Content-Type: application/json

{
"title": "Fourth post",
"body": "Body o ff"
}


###
GET http://localhost:3000/yee-newblog/posts

###

###
GET http://localhost:3000/brand-brand-new-newblog/posts/fe9a689e-87bc-4586-9071-03cddeebaa16

###

PATCH http://localhost:3000/create/update/brand-brand-new-newblog
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUyOGIxOTY1LTk1NjktNGVjYS04MDUxLTgyMTU0NmJkNmRkOSIsImlhdCI6MTc2MjU3NDQxMiwiZXhwIjoxNzYyNTc2MjEyfQ.9Hq8htTbNWMuTfzlK2Ci9zW7ZOnBp6FixtipG1kU868
Content-Type: application/json

{
  "blogName": "Brand new newblog"
}

###

PATCH http://localhost:3000/brand-brand-new-newblog/posts/fe9a689e-87bc-4586-9071-03cddeebaa16/edit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMGM4YmI3LWNmMDUtNDA3NC04Yjc0LWFmOTVlYzdmZTA1ZiIsImlhdCI6MTc2MjY3MDEwNCwiZXhwIjoxNzYyNjcxOTA0fQ.dWlhHJXkfFWmU1VztQTgMxrkRYFciTvNXGPPSYV1FNk
Content-Type: application/json

{
  "body": " Updated body oo ff",
  "id": "0"
}

###

DELETE http://localhost:3000/brand-brand-new-newblog/posts/162c6ca0-4729-4237-99fd-0b9c500b3617/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMGM4YmI3LWNmMDUtNDA3NC04Yjc0LWFmOTVlYzdmZTA1ZiIsImlhdCI6MTc2MjY3MDEwNCwiZXhwIjoxNzYyNjcxOTA0fQ.dWlhHJXkfFWmU1VztQTgMxrkRYFciTvNXGPPSYV1FNk
Content-Type: application/json

###

DELETE http://localhost:3000/create/delete/blog-name
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZkMzkxNzNmLTY3OTUtNDU4MS1iN2Q5LWNjOWM1MTlkZTBlYiIsIl9pZCI6IjY5MmMzY2U4ZjkzNTY5NmNiNDJkMDZmOSIsImlhdCI6MTc2NTc5MjM3NCwiZXhwIjoxNzY1Nzk0MTc0fQ.LynX3TRGEz8V17CTgbQ1MSuGiSnExdTwKBhV0KxEZO4
Content-Type: application/json